flux:
  dashboard-menu-label: Dashboard
  reconcile-action-label: Reconcile
  reconcile-source-action-label: Reconcile source
  relatedResources:
    relationshipColumn:
      label: Relationship
  kustomization:
    section:
      related:
        label: Related Resources
      inventory:
        label: Inventory
  helmrelease:
    section:
      related:
        label: Related Resources
      inventory:
        label: Inventory
  helmchart:
    section:
      related:
        label: Related Resources
  gitrepository:
    section:
      related:
        label: Related Resources
  ocirepository:
    section:
      related:
        label: Related Resources
  bucket:
    section:
      related:
        label: Related Resources
  helmrepository:
    section:
      related:
        label: Related Resources
